safe: true
future: false
markdown: kramdown
permalink: pretty
timezone: Europe/Paris

defaults:
  - scope:
      path: ""
    values:
      layout: standard

collections:
  projects:

exclude:
  run_development_cycle.sh
